### ISSUE TITLE
Locks up entire shell when dragging a window to the bottom

### ISSUE THREAD

**Issue by cassidyjames** [donadigo/blockbuster#4]
I turned on the "Snap a window to bottom" feature, and now every time I drag a window near the bottom of the display, it locks up the entire shell and I need to `REISUB` to reboot.

**Comment by donadigo** [comment]
Did you test it on a laptop or a desktop? Specifically, did you use a touchpad or a regular mouse? I'm quite lost on where this feature would fail (although I have some pointers) and would like to know this.

**Comment by cassidyjames** [comment]
@donadigo a laptop, both with an external display and without. I believe I was using a USB mouse.

**Comment by donadigo** [comment]
Yeah I don't know what's happening there. I just tested with a laptop with a mouse and no crashes here.

**Comment by donadigo** [comment]
Going to close this for now since the feature was removed in the current version.
